[package]
name = "trip"
version = "0.4.0"
edition = "2024"

[dependencies]
common-game = { git = "https://github.com/unitn-ap-2025/common.git", tag = "v2.0.0"}
crossbeam-channel = "0.5.15"
log = "0.4.29"

[dev-dependencies]
env_logger = "0.11.8"
